local env=dofile(arg[2]..'/support/cet_mock.lua')
local app=env.app
assert(app.version=='0.80.0' and app.checkpoints)
local object=app.model:add_object({id='checkpoint_object',name='Test chair',kind='entity',template='base\\chair.ent',transform={position={x=1,y=2,z=3},rotation={yaw=0}}})
assert(app.placement:spawn(object))
local first=assert(app.checkpoints:create({name='Before edit'}))
object.transform.position.x=7
assert(app.placement:refresh(object))
app.model:add_object({id='new_checkpoint_object',name='New prop',template='base\\prop.ent'})
local second=assert(app.checkpoints:create({name='After edit'}))
local cp_data=assert(app.checkpoints:_load(first.id))
assert(cp_data.project.objects[1].runtime==nil,'runtime handles must not be snapshotted')
local diff=assert(app.checkpoints:diff(first.id,second.id))
assert(diff.objects.counts.moved==1 and diff.objects.moved[1].id=='checkpoint_object')
assert(diff.objects.counts.added==1 and diff.objects.added[1].id=='new_checkpoint_object')
local list=app.checkpoints:list();assert(list.count==2)
local restored=assert(app.checkpoints:restore(first.id))
assert(restored.restored and #app.model.data.objects==1 and app.model.data.objects[1].transform.position.x==1)
assert(app.dirty and app.model.undo_stack[#app.model.undo_stack].__history.label=='Restore checkpoint Before edit')
assert(restored.runtime_sync and restored.runtime_sync.has_changes,'restore should offer runtime sync when a tracked entity differs')
assert(app:sync_runtime().updated==1)
local duplicate,duplicate_err=app.checkpoints:create({name='before EDIT'})
assert(not duplicate and duplicate_err:find('already exists',1,true))
local missing,missing_err=app.checkpoints:restore('../project')
assert(not missing and missing_err:find('invalid checkpoint id',1,true))
local draw_ok,draw_err=pcall(function() app.ui.tools:draw_checkpoints() end)
assert(draw_ok,draw_err)
print('LocationStudio Project Checkpoints: OK')
