local env=dofile(arg[2]..'/support/cet_mock.lua')
local app=env.app
assert(app.version=='0.56.0')
local premise=assert(app.actions:create_premise_from_player('Combat encounter test','interior'))
local function create_npc(name,record,x)
    local asset=app.model:add_asset({name=name,kind='entity_record',template=record,size={x=1,y=1,z=1},metadata={world_builder={definition_key='entity_record',module_path='entity/entityRecord',resource_path=record,resource_name=name,entry={name=name,fileName=name,data={modulePath='entity/entityRecord',spawnData=record,app='default'}}}}})
    return assert(app.actions:create_npc_population({asset_id=asset.id,name=name,premise_id=premise.id,transform={position={x=x,y=2,z=3},rotation={yaw=45}},source='origin'}))
end
local npc1=create_npc('Gang guard A','Character.combat_test_a',10)
local npc2=create_npc('Gang guard B','Character.combat_test_b',20)
local area=assert(app.model:add_volume({premise_id=premise.id,name='Combat area',purpose='combat_area',shape='box',size={x=12,y=12,z=3},transform={position={x=15,y=2,z=3}}}))
local trigger=assert(app.model:add_volume({premise_id=premise.id,name='Combat trigger',purpose='trigger',shape='box',size={x=4,y=4,z=3},transform={position={x=0,y=2,z=3}},metadata={questforge={fact_name='combat_entered',value=1}}}))
local encounter=assert(app.actions:create_combat_encounter({premise_id=premise.id,name='Clinic ambush',area_volume_id=area.id,trigger_volume_id=trigger.id,activation_fact='combat_enabled',activation_value=1}))
assert(app.actions:update_combat_encounter({id=encounter.id,patch={reset_fact='combat_reset',reset_value=1}}))
local group=assert(app.actions:create_encounter_group({encounter_id=encounter.id,name='Tyger Claws',faction='tyger_claws',attitude='hostile',npc_ids={npc1.id,npc2.id},spacing=2}))
local wave1=assert(app.actions:create_encounter_wave({encounter_id=encounter.id,name='Initial defenders',group_ids={group.id},activation='volume',trigger_volume_id=trigger.id}))
local wave2=assert(app.actions:create_encounter_wave({encounter_id=encounter.id,name='Reinforcements',group_ids={group.id},activation='after_wave',after_wave_id=wave1.id,delay_seconds=12}))
local wave3=assert(app.actions:create_encounter_wave({encounter_id=encounter.id,name='Fact gated',group_ids={group.id},activation='fact',fact_name='backup_called',fact_value=1}))
assert(wave1.activation=='volume' and wave2.after_wave_id==wave1.id and wave2.delay_seconds==12 and wave3.fact_name=='backup_called')
assert(app.actions:set_encounter_faction_relation({encounter_id=encounter.id,source_faction='tyger_claws',target_faction='player',attitude='hostile'}).attitude=='hostile')
local invalid,err=app.actions:create_encounter_wave({encounter_id=encounter.id,name='Bad fact',group_ids={group.id},activation='fact',fact_name='not a fact'})
assert(not invalid and err:find('invalid characters',1,true))
app.live_tools={spawned={},spawn_record=function(self,args) local out={key='temp'..tostring(#self.spawned+1),tag=args.tag,record=args.record,position=args.position};self.spawned[#self.spawned+1]=out;return out end,
    despawn_tag=function(self,tag) self.last_reset=tag;local count=#self.spawned;self.spawned={};return {deleted=tag,count=count} end}
local tested=assert(app.actions:test_combat_encounter(encounter.id,wave1.id));assert(tested.count==2 and #app.live_tools.spawned==2)
assert(app.live_tools.spawned[1].position.x==10 and app.live_tools.spawned[2].position.x==20)
assert(app.actions:reset_combat_encounter(encounter.id).deleted==encounter.test_tag and #app.live_tools.spawned==0)
local export_path='exports/test_combat_encounters.json';assert(app.storage:export_questforge(app.model,export_path))
local handoff=assert(json.decode(assert(app.util.read_file(export_path))))
local exported=assert(handoff.combat_encounters[1]);assert(exported.id==encounter.id and exported.combat_area.id==area.id and exported.trigger_volume.id==trigger.id)
assert(#exported.groups==1 and #exported.groups[1].members==2 and #exported.waves==3)
assert(exported.waves[2].after_wave_id==wave1.id and exported.waves[2].delay_seconds==12 and exported.waves[3].fact_name=='backup_called')
assert(exported.faction_relations[1].target_faction=='player' and exported.runtime_status=='handoff_only')
app.ui.spatial.combat_encounter_id=encounter.id;app.ui.spatial:draw_combat_encounters(premise)
assert(env.labels['CREATE GROUP FROM SELECTED NPC'] and env.labels['CREATE WAVE'] and env.labels['RESET TEST ENCOUNTER'])
assert(app.actions:delete_encounter_group({encounter_id=encounter.id,group_id=group.id}).deleted)
assert(#wave1.group_ids==0 and #wave2.group_ids==0)
print('LocationStudio combat encounter authoring, temp test/reset, and export: OK')
