local env=dofile(arg[2]..'/support/cet_mock.lua')
local app=env.app
assert(app.version=='0.82.0' and app.device_logic)
local graph=assert(app.device_logic:create({name='Clinic entrance logic'}))
local door=assert(app.device_logic:add_node({graph_id=graph.id,kind='door',name='Front Door'}))
local terminal=assert(app.device_logic:add_node({graph_id=graph.id,kind='terminal',name='Reception Panel'}))
local fact=assert(app.device_logic:add_node({graph_id=graph.id,kind='fact',name='Entry unlocked',config={fact_name='clinic.entry_unlocked',value=1}}))
local action=assert(app.device_logic:add_node({graph_id=graph.id,kind='action',name='Unlock Door',config={operation='unlock',target=door.id}}))
assert(not app.device_logic:add_node({graph_id=graph.id,kind='fact',name='Bad fact',config={fact_name='bad fact'}}))
assert(not app.device_logic:add_node({graph_id=graph.id,kind='action',name='Bad action',config={operation='arbitrary_lua'}}))
local link=assert(app.device_logic:add_link({graph_id=graph.id,from_id=terminal.id,to_id=action.id,trigger='interact',condition_fact='clinic.entry_unlocked',condition_value=1,native_operation='Unlock'}))
local duplicate,why=app.device_logic:add_link({graph_id=graph.id,from_id=terminal.id,to_id=action.id,trigger='interact'})
assert(duplicate.id==link.id and why=='link already exists')
assert(not app.device_logic:add_link({graph_id=graph.id,from_id=terminal.id,to_id='missing'}))
local report=assert(app.device_logic:validate(graph.id))
assert(report.graphs[1].status=='needs_native_resources' and report.graphs[1].native_runtime_execution==false and #report.graphs[1].warnings>=2)
local listed=assert(app.bridge:handle({op='device_logic_graph_list',args={}}))
assert(#listed.graphs==1 and #listed.graphs[1].nodes==4)
local fetched=assert(app.bridge:handle({op='device_logic_graph_get',args={graph_id=graph.id}}))
assert(fetched.id==graph.id and #fetched.links==1)
local bridge_report=assert(app.bridge:handle({op='device_logic_validate',args={graph_id=graph.id}}))
assert(bridge_report.graphs[1].status=='needs_native_resources')
assert(app.storage:export_questforge(app.model,'exports/test_device_logic.json'))
local handoff=assert(json.decode(assert(app.util.read_file('exports/test_device_logic.json'))))
assert(#handoff.device_logic_graphs==1 and handoff.device_logic_graphs[1].id==graph.id and handoff.device_logic_graphs[1].links[1].trigger=='interact')
local deleted=assert(app.device_logic:delete_node(graph.id,terminal.id))
assert(deleted.deleted and deleted.removed_links==1 and #graph.links==0)
assert(app.device_logic:delete_graph(graph.id).deleted and #app.model.data.device_logic_graphs==0)

local ui=app.ui.spatial
local ui_graph=assert(app.device_logic:create({name='UI graph'}));ui.logic_graph_id=ui_graph.id
ui:draw_device_logic(nil)
assert(env.labels['CREATE GRAPH'] and env.labels['ADD NODE'] and env.labels['CONNECT NODES'] and env.labels['VALIDATE NATIVE READINESS'])
print('LocationStudio Device Logic graph authoring, validation, bridge and editor UI: OK')
