local env=dofile(arg[2]..'/support/cet_mock.lua')
local app=env.app
local door=app.model:add_asset({name='Clinic door',category='Game Entity',kind='entity',template='base/doors/test_interactive.ent',size={x=1,y=1,z=2}})
local created,warning=app.actions:create_interactable({kind='door',asset_id=door.id,name='Locked clinic entrance',source='origin',spawn=false,
    entity_record='Device.clinic_door',lock_state='locked',fact_name='clinic_door_opened',fact_value=1})
assert(created and warning and warning:find('native game interaction wiring',1,true),'create should place data and disclose native setup requirement')
local saved=created.metadata.interactable
assert(created.kind=='interactable' and saved.kind=='door' and saved.entity_record=='Device.clinic_door')
assert(saved.lock_state=='locked' and saved.fact_name=='clinic_door_opened' and saved.fact_value==1)
local updated=assert(app.actions:update_interactable(created.id,{lock_state='unlocked',fact_name='clinic_door_used',fact_value=2}))
assert(updated.metadata.interactable.lock_state=='unlocked' and updated.metadata.interactable.fact_value==2)
assert(not app.actions:update_interactable(created.id,{fact_name='invalid fact'}),'invalid fact must be rejected')
local chest=app.actions:create_interactable({kind='loot_container',asset_id=door.id,source='origin',spawn=false,loot_table='LootTables.clinic_supply',lock_state='locked'})
assert(chest and chest.metadata.interactable.loot_table=='LootTables.clinic_supply')
assert(not app.actions:create_interactable({kind='loot_container',asset_id=door.id,source='origin',spawn=false,loot_table='Bad.Table'}),'invalid loot table must be rejected')
assert(not app.actions:create_interactable({kind='shard',asset_id=door.id,source='origin',spawn=false,item_record='bad'}),'shard must require an Items record')
local shard=assert(app.actions:create_interactable({kind='shard',asset_id=door.id,source='origin',spawn=false,item_record='Items.DataShard_Clinic',lock_state='not_applicable'}))
assert(shard.metadata.interactable.item_record=='Items.DataShard_Clinic')
local mesh=app.model:add_asset({name='Plain mesh',template='base/props/crate.mesh'})
assert(not app.actions:create_interactable({kind='item',asset_id=mesh.id,item_record='Items.Test',source='origin',spawn=false}),'mesh-only asset must not be accepted as interactive')
local listed=assert(app.bridge:handle({id='list-interactables',op='list_interactables'}))
assert(listed.count==3,'list must expose placed interactables')
local path='exports/test_interactables_questforge.json'
assert(app.storage:export_questforge(app.model,path))
local handoff=assert(json.decode(assert(app.util.read_file(path))))
assert(#handoff.interactable_handoff==3)
assert(handoff.interactable_handoff[1].native_setup_required and handoff.interactable_handoff[1].setup_status=='authoring_only')
assert(handoff.interactable_handoff[1].fact_on_interact.name=='clinic_door_used')
assert(handoff.interactable_handoff[2].loot_table=='LootTables.clinic_supply')
print('interactables_runtime_test: OK')
