local env=dofile(arg[2]..'/support/cet_mock.lua')
local app=env.app
local object=assert(app.model:add_object({name='Appearance test mesh',kind='mesh',template='base\\environment\\architecture\\walls\\game_wall.mesh',layer='decoration',transform={position={x=1,y=2,z=3},rotation={roll=0,pitch=0,yaw=0}},size={x=1,y=1,z=1},enabled=true,metadata={world_builder={definition_key='mesh_static',category='Mesh',variant='Mesh',class_module='modules/classes/spawn/mesh/mesh',module_path='mesh/mesh',resource_name='game_wall',resource_path='base\\environment\\architecture\\walls\\game_wall.mesh',apply_scale=true,entry={name='game_wall',fileName='game_wall',data={spawnData='base\\environment\\architecture\\walls\\game_wall.mesh',app='default'}}}}}))
app.selected_object_id=object.id
assert(app.placement:spawn(object))
local listed=assert(app.mesh_appearance:list())
assert(#listed.appearances==2 and listed.appearances[2]=='damaged')
local preview=assert(app.mesh_appearance:preview({appearance='damaged'}));assert(preview.preview)
local handle=app.runtime_shell.handles[object.id]
assert(handle.spawnable.entity:FindComponentByName('mesh').meshAppearance=='damaged')
assert(not app.dirty,'preview must not save project data')
assert(app.mesh_appearance:cancel({object_id=object.id}).cancelled)
assert(handle.spawnable.entity:FindComponentByName('mesh').meshAppearance=='default')
assert(app.mesh_appearance:preview({appearance='damaged'}))
local applied=assert(app.mesh_appearance:apply({appearance='damaged'}))
assert(applied.saved and object.metadata.world_builder.entry.data.app=='damaged')
assert(app.dirty)
assert(not app.mesh_appearance:preview({appearance='not-a-real-variant'}),'unlisted appearance must fail')
local decal=assert(app.mesh_appearance:create_decal({query='test_decal',name='Clinic decal',source='aim',width=2,height=1,alpha=0.7,spawn=true}))
assert(decal.spawned and decal.object.metadata.world_builder.definition_key=='decal')
assert(decal.object.metadata.world_builder.entry.data.spawnData=='base\\decal\\test.mi')
assert(decal.object.metadata.world_builder.entry.data.alpha==0.7)
assert(decal.object.metadata.world_builder.entry.data.scale.x==2 and decal.object.metadata.world_builder.entry.data.scale.y==1)
assert(decal.object.runtime and decal.object.runtime.spawned)
print('mesh_appearance_runtime_test: OK')
