local env=dofile(arg[2]..'/support/cet_mock.lua')
local app=env.app
assert(app.version=='0.71.0')
local premise=assert(app.actions:create_premise_from_player('NPC Route Test','interior'))
local record='Character.test_route_guard'
local asset=app.model:add_asset({name='Route Guard',kind='entity_record',template=record,size={x=1,y=1,z=1},metadata={world_builder={definition_key='entity_record',module_path='entity/entityRecord',resource_path=record,resource_name='Route Guard',entry={name='Route Guard',fileName='Route Guard',data={modulePath='entity/entityRecord',spawnData=record,app='default'}}}}})
local npc=assert(app.actions:create_npc_population({asset_id=asset.id,name='Route Guard',premise_id=premise.id,transform={position={x=0,y=0,z=0},rotation={yaw=0}},source='origin'}))
local route=assert(app.actions:create_npc_route({npc_id=npc.id,name='Guard Loop',loop=true}))
assert(route.npc_id==npc.id and #route.waypoints==0)
local a=assert(app.actions:add_npc_route_waypoint({route_id=route.id,variant='patrol',name='Door',transform={position={x=1,y=2,z=3},rotation={yaw=10}},wait_seconds=2,facing_yaw=90,speed=0.8}))
local b=assert(app.actions:add_npc_route_waypoint({route_id=route.id,variant='patrol',name='Desk',transform={position={x=4,y=5,z=6},rotation={yaw=20}},transition='walk'}))
local c=assert(app.actions:add_npc_route_waypoint({route_id=route.id,variant='alert',name='Alarm',transform={position={x=7,y=8,z=9},rotation={yaw=30}}}))
assert(a.wait_seconds==2 and a.facing_yaw==90 and a.speed==0.8 and c.variant=='alert')
assert(app.actions:update_npc_route_waypoint({route_id=route.id,waypoint_id=b.id,patch={transform={position={x=7,y=8,z=9},rotation={yaw=60}},wait_seconds=4,branch_fact='alarm_active',branch_value=1,branch_target_id=a.id}}))
assert(app.actions:move_npc_route_waypoint({route_id=route.id,waypoint_id=b.id,delta=-1}))
assert(route.waypoints[1].id==b.id)
local invalid,err=app.actions:update_npc_route_waypoint({route_id=route.id,waypoint_id=b.id,patch={branch_target_id='missing'}})
assert(not invalid and err:find('branch_target_id',1,true))
local handoff_path='exports/test_npc_route_handoff.json'
assert(app.storage:export_questforge(app.model,handoff_path))
local handoff=assert(json.decode(assert(app.util.read_file(handoff_path))))
local exported=assert(handoff.npc_ai_routes[1]);assert(exported.npc_id==npc.id and exported.character_record==record and exported.loop)
assert(exported.waypoints[1].id==b.id and exported.waypoints[1].branch.fact=='alarm_active' and exported.waypoints[1].next_waypoint_id==a.id)
assert(exported.waypoints[1].position[1]==7 and exported.waypoints[1].yaw==60)
assert(exported.alert_waypoints[1].name=='Alarm' and exported.runtime_status=='handoff_only')
app.ui.spatial.npc_route_npc_id=npc.id;app.ui.spatial.npc_route_id=route.id;app.ui.spatial.npc_route_variant='patrol';app.ui.spatial.npc_route_wp_edit_id=b.id
app.ui.spatial:draw_npc_routes(premise)
assert(env.labels['ADD WAYPOINT AT PLAYER'] and env.labels['SAVE WAYPOINT SETTINGS'] and env.labels['DELETE ROUTE'])
assert(app.actions:delete_npc_route_waypoint({route_id=route.id,waypoint_id=c.id,variant='alert'}).deleted)
assert(app.actions:delete_npc_route(route.id));assert(#app.model.data.npc_routes==0)
assert(app.actions:create_npc_route({npc_id=npc.id,name='Cleanup route'}))
assert(app.model:delete_object(npc.id));assert(#app.model.data.npc_routes==0,'deleting the population object must cascade its routes')
print('LocationStudio NPC patrol route authoring and export: OK')
